
### Create a new order
POST http://localhost:8000/orders/create
Content-Type: application/json

{
   "user":{
        "name": "Jhon Dou",
        "phone": "09362901456",
        "email": "test@gmail.com",
        "addres": "dsadwa"
   },
    "orderItems": [{
        "productId" : 1,
        "quantity": 2
    }]
}

### Create a new user
POST http://localhost:8000/user/create
Content-Type: application/json

{
   "name": "Jhon Dou",
   "phone": "0936290144",
   "email": "test@gmail.com",
   "addres": "dsadwa"
   }

###Search orders
GET http://localhost:8000/orders/search?email=test@gmail.com&phone=09362901456


###Get order by Id
GET http://localhost:8000/orders/6

###Get all shops
GET http://localhost:8000/shops

###
GET http://localhost:8000/shops/3/products